import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Providers } from './providers/providers';
import { Footer } from '../components/ui/Footer';
import { Navbar } from '../components/ui/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog App',
  description: 'Generated by Ariel Elias',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className='containery'>
            <main className="wrapper">
              <Navbar />
                {children}
              <Footer />
            </main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
